server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: true
    default-schema: currency_sch
    change-log: classpath:db/changelog_init.xml
    liquibase-schema: public
  main:
    banner-mode: off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    hikari:
      schema: currency_sch
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        hbm2ddl:
          auto: none
app:
  currency:
    url: https://cbr.ru/scripts/XML_daily.asp
scheduler:
  update-interval: '0 0 * * * *'

